<?php
require_once 'PHPUnit/Framework.php';

/**
 * Test class for MvcPackage.
 * Generated by PHPUnit on 2010-04-26 at 19:48:49.
 */
class MvcPackageTest extends PHPUnit_Framework_TestCase
{
	protected function setUp()
	{
	}

	protected function tearDown()
	{
	}

	public function testClassIsAbstract()
	{
		$reflection = new ReflectionClass('MvcPackage');
		$this->assertThat(
			$reflection->isAbstract(),
			$this->equalTo(true)
		);
	}

	public function testRegister()
	{
		$stub = new MvcPackageStub_MvcPackageTest();
		$paths = new PathCollection();
		$stub->register($this->getMock('IContainerBuilder'), $paths);

		// proof of concept
		$this->assertThat(
			$paths->getPaths('Mvc.controllers'),
			$this->equalTo(array(FIXTURES_ROOT.'/Components'))
		);
	}
}

class MvcPackageStub_MvcPackageTest extends MvcPackage
{
	public function registerClassLoaders() {}
	public function getPackagename() { return 'Mvc'; }
	public function registerWiring(IContainerBuilder $container) {}
	public function registerPaths() { return array(FIXTURES_ROOT.'/Components'); }
	public function registerControllerPaths() { return array(FIXTURES_ROOT.'/Components'); }
	public function registerCommandPaths() {}
	public function registerViewPaths() {}
}
