<?php
require_once 'PHPUnit/Framework.php';

/**
 * Test class for AbstractClassLoader.
 * Generated by PHPUnit on 2010-04-18 at 19:28:39.
 */
class AbstractClassLoaderTest extends PHPUnit_Framework_TestCase
{
	protected function setUp()
	{
	}

	protected function tearDown()
	{
	}

	public function testIsAbstractClass()
	{
		$reflection = new ReflectionClass('AbstractClassLoader');
		$this->assertTrue($reflection->isAbstract());
	}
}
