<?php
require_once 'PHPUnit/Framework.php';

/**
 * Test class for FlatFolderLoader.
 * Generated by PHPUnit on 2010-04-18 at 19:28:39.
 */
class FlatFolderClassLoaderTest extends PHPUnit_Framework_TestCase
{
	/**
	 * @var FlatFolderLoader
	 */
	protected $object;

	protected function setUp()
	{
		$this->object = new FlatFolderClassLoader(FIXTURES_ROOT.'/Components/Package');
	}

	protected function tearDown()
	{
	}

	public function testResourceExists()
	{
		$this->assertTrue($this->object->resourceExists('FourClassModel'));
		$this->assertFalse($this->object->resourceExists('UndefinedClassModel'));
	}

	public function testImportResource()
	{
		$class = 'FourClassModel';
		$this->assertFalse(class_exists($class));
		$this->object->importResource($class);
		$this->assertTrue(class_exists($class));
	}
}
