<?php
require_once 'PHPUnit/Framework.php';

/**
 * Test class for RequestBaseUrlStrategy.
 * Generated by PHPUnit on 2010-04-17 at 22:19:55.
 */
class RequestBasePathStrategyTest extends PHPUnit_Framework_TestCase
{
	/**
	 * @var RequestBaseUrlStrategy
	 */
	protected $object;

	protected function setUp()
	{
		$mock = $this->getMock('IRequest');
		$mock->expects($this->any())
			->method('getBasePath')
			->will($this->returnValue('http://localhost/index.php'));
		$this->object = new RequestBasePathStrategy($mock);
	}

	protected function tearDown()
	{
	}

	public function testGetUrl()
	{
		$this->assertEquals($this->object->getUrl(), 'http://localhost/index.php');
	}
}
