<?php
require_once 'PHPUnit/Framework.php';

/**
 * Test class for ValueUrlStrategy.
 * Generated by PHPUnit on 2010-04-17 at 17:32:14.
 */
class ValueUrlStrategyTest extends PHPUnit_Framework_TestCase
{
	/**
	 * @var ValueUrlStrategy
	 */
	protected $object;

	protected function setUp()
	{
		$this->object = new ValueUrlStrategy('http://my.application.com/');
	}

	protected function tearDown()
	{
	}

	public function testGetUrl()
	{
		$this->assertThat(
			$this->object->getUrl(),
			$this->equalTo('http://my.application.com/')
		);
	}
}
