<?php
require_once 'PHPUnit/Framework.php';

/**
 * Test class for FileLogMessageHandler.
 * Generated by PHPUnit on 2010-04-27 at 20:11:59.
 */
class FileLogMessageHandlerTest extends PHPUnit_Framework_TestCase
{
	/**
	 * @var FileLogMessageHandler
	 */
	protected $object;

	/**
	 * @var string
	 */
	protected $filename;

	protected function setUp()
	{
		$this->filename = tempnam(sys_get_temp_dir(), 'Test');
		$this->object = new FileLogMessageHandler($this->filename);
	}

	protected function tearDown()
	{
		$this->object->__destruct();
		unlink($this->filename);
	}

	public function testHandleLogMessage()
	{
		$log = new LogMessage('message');
		$this->object->handle($log);

		$this->assertThat(
			file_get_contents($this->filename),
			$this->equalTo('message'.PHP_EOL)
		);
	}
}
