<?php
require_once 'PHPUnit/Framework.php';

/**
 * Test class for LogMessageHandlerComposite.
 * Generated by PHPUnit on 2010-04-27 at 17:46:55.
 */
class LogMessageHandlerCompositeTest extends PHPUnit_Framework_TestCase
{
	/**
	 * @var LogMessageHandlerComposite
	 */
	protected $object;

	/**
	 * @var array of ILogMessageHandler
	 */
	protected $mocks;

	protected function setUp()
	{
		$this->mocks = array();
		for ($i = 0; $i < 3; $i++)
		{
			$this->mocks[$i] = $this->getMock('ILogMessageHandler');
			$this->mocks[$i]->expects($this->once())->method('handle')
				->with($this->isInstanceOf('ILogMessage'));
		}

		$this->object = new LogMessageHandlerComposite($this->mocks);
	}

	protected function tearDown()
	{
	}

	public function testHandle()
	{
		$log = $this->getMock('ILogMessage');
		$this->object->handle($log);
	}
}
