<?php
require_once 'PHPUnit/Framework.php';

/**
 * Test class for ContainerPhpFileLoader.
 * Generated by PHPUnit on 2010-04-26 at 15:09:03.
 */
class ContainerPhpFileLoaderTest extends PHPUnit_Framework_TestCase
{
	/**
	 * @var ContainerPhpFileLoader
	 */
	protected $object;

	protected function setUp()
	{
		$mock = $this->getMock('IContainerLoader');
		$mock->expects($this->any())->method('load')->will($this->returnValue(
			array('some values')
		));
		$this->object = new ContainerPhpFileLoader($mock);
	}

	protected function tearDown()
	{
	}

	public function testLoad()
	{
		$builder = $this->object->load(FIXTURES_ROOT.'/Components/DependencyInjection/Loader/SampleArrayConfig.php');
		$this->assertThat(
			$builder,
			$this->equalTo(array('some values'))
		);
	}

	public function testLoad_UndefinedPath()
	{
		$this->setExpectedException('RuntimeException');
		$this->object->load(FIXTURES_ROOT.'/Undefined/Path/To/File.php');
	}
}
