<?php
require_once 'PHPUnit/Framework.php';

/**
 * Test class for RouterFactory.
 * Generated by PHPUnit on 2010-04-07 at 13:58:53.
 */
class RouterFactoryTest extends PHPUnit_Framework_TestCase
{
	/**
	 * @var RouterFactory
	 */
	protected $object;

	protected function setUp()
	{
		$this->object = new RouterFactory();
	}

	protected function tearDown()
	{
	}

	public function testCreateCompiledRule()
	{
		$routingRuleMock = $this->getMock('IRoutingRule');
		$rule = $this->object->createCompiledRule($routingRuleMock, null);
		$this->assertThat($rule, $this->isInstanceOf('CompiledRule'));
	}

	public function testCreateRoute()
	{
		$route = $this->object->createRoute();
		$this->assertThat($route, $this->isInstanceOf('Route'));
	}
}
