<?php
require_once 'PHPUnit/Framework.php';

/**
 * Test class for UrlCreator.
 * Generated by PHPUnit on 2010-03-24 at 08:51:51.
 */
class UrlCreatorTest extends PHPUnit_Framework_TestCase
{
	/**
	 * @var UrlCreator
	 */
	protected $object;

	/**
	 * @var RoutingRule
	 */
	protected $rule;

	protected function setUp()
	{
		$this->object = new UrlCreator;
		$this->rule = new RoutingRule(
			'some_rule',
			'/{controller}/{action}/{year}',
			array(
				'controller' => 'Default'
			),
			array(
				'controller' => 'string',
				'action'     => 'string',
				'year'       => 'int',
			)
		);
	}

	protected function tearDown()
	{
	}

	public function testMakeUrl_WithNoParams()
	{
		$this->setExpectedException('InvalidArgumentException');
		$url = $this->object->makeUrl(array(), $this->rule);
	}

	public function testMakeUrl_WithAllParams()
	{
		$url = $this->object->makeUrl(array(
			'controller' => 'main',
			'action'     => 'my-action',
			'year'       => '2010'
		), $this->rule);

		$this->assertThat($url, $this->equalTo('/main/my-action/2010'));
	}

	public function testMakeUrl_WithDefaultParam()
	{
		$url = $this->object->makeUrl(array(
			'action' => 'my-action',
			'year'   => '2010'
		), $this->rule);

		$this->assertThat($url, $this->equalTo('/Default/my-action/2010'));
	}
}
