<?php
require_once 'PHPUnit/Framework.php';

/**
 * Test class for ActionNameStrategy.
 * Generated by PHPUnit on 2010-04-14 at 12:52:50.
 */
class ActionNameStrategyTest extends PHPUnit_Framework_TestCase
{
	/**
	 * @var ActionNameStrategy
	 */
	protected $object;

	protected function setUp()
	{
		$this->object = new ActionNameStrategy();
	}

	protected function tearDown()
	{
	}

	public function testGetName()
	{
		$this->assertThat(
			$this->object->getName('some-action-name'),
			$this->equalTo('someActionNameAction')
		);
	}
}
