<?php
require_once 'PHPUnit/Framework.php';

/**
 * Test class for CommandNameStrategy.
 * Generated by PHPUnit on 2010-04-14 at 12:53:21.
 */
class CommandNameStrategyTest extends PHPUnit_Framework_TestCase
{
	/**
	 * @var CommandNameStrategy
	 */
	protected $object;

	protected function setUp()
	{
		$this->object = new CommandNameStrategy();
	}

	protected function tearDown()
	{
	}

	public function testGetClassName()
	{
	}
}
