<?php
require_once 'PHPUnit/Framework.php';

/**
 * Test class for CommandNameStrategy.
 * Generated by PHPUnit on 2010-04-14 at 12:53:21.
 */
class CommandNameStrategyTest extends PHPUnit_Framework_TestCase
{
	/**
	 * @var CommandNameStrategy
	 */
	protected $object;

	protected function setUp()
	{
		$this->object = new CommandNameStrategy();
	}

	protected function tearDown()
	{
	}

	public function testGetName()
	{
		$this->assertThat(
			$this->object->getName('some-inline-action'),
			$this->equalTo('SomeInlineAction')
		);

		$this->assertThat(
			$this->object->getName('underscored_name'),
			$this->equalTo('UnderscoredName')
		);
	}

	public function testGetClassName()
	{
		$this->assertThat(
			$this->object->getClassName('Search/Special/Location'),
			$this->equalTo('LocationCommand')
		);

		$this->assertThat(
			$this->object->getClassName('Simple-Location'),
			$this->equalTo('SimpleLocationCommand')
		);

		$this->assertThat(
			$this->object->getClassName('Complicated/Within_and-nested/class'),
			$this->equalTo('ClassCommand')
		);
	}

	public function testGetFileName()
	{
		$this->assertThat(
			$this->object->getFileName('Search/Special/Location'),
			$this->equalTo('Search/Special/LocationCommand')
		);

		$this->assertThat(
			$this->object->getFileName('Complicated/Within_and-nested/class'),
			$this->equalTo('Complicated/WithinAndNested/ClassCommand')
		);

		$this->assertThat(
			$this->object->getFileName('simple-Location'),
			$this->equalTo('SimpleLocationCommand')
		);
	}
}
