<?php
require_once 'PHPUnit/Framework.php';

/**
 * Test class for ControllerNameStrategy.
 * Generated by PHPUnit on 2010-04-14 at 12:53:40.
 */
class ControllerNameStrategyTest extends PHPUnit_Framework_TestCase
{
	/**
	 * @var ControllerNameStrategy
	 */
	protected $object;

	protected function setUp()
	{
		$this->object = new ControllerNameStrategy();
	}

	protected function tearDown()
	{
	}

	public function testGetClassName()
	{
	}
}
