<?php
require_once 'PHPUnit/Framework.php';

/**
 * Test class for ControllerNameStrategy.
 * Generated by PHPUnit on 2010-04-14 at 12:53:40.
 */
class ControllerNameStrategyTest extends PHPUnit_Framework_TestCase
{
	/**
	 * @var ControllerNameStrategy
	 */
	protected $object;

	protected function setUp()
	{
		$this->object = new ControllerNameStrategy();
	}

	protected function tearDown()
	{
	}

	public function testGetName()
	{
		$this->assertThat(
			$this->object->getName('some-inline-controller'),
			$this->equalTo('SomeInlineController')
		);

		$this->assertThat(
			$this->object->getName('underscored_name'),
			$this->equalTo('UnderscoredName')
		);
	}

	public function testGetClassName()
	{
		$this->assertThat(
			$this->object->getClassName('SearchSpecial'),
			$this->equalTo('SearchSpecialController')
		);

		$this->assertThat(
			$this->object->getClassName('Simple-Location'),
			$this->equalTo('SimpleLocationController')
		);

		$this->assertThat(
			$this->object->getClassName('ComplicatedWithin_and-nested class'),
			$this->equalTo('ComplicatedWithinAndNestedClassController')
		);
	}

	public function getFileName()
	{
		$this->assertThat(
			$this->object->getName('some-inline-controller'),
			$this->equalTo('SomeInlineController')
		);

		$this->assertThat(
			$this->object->getName('underscored_name'),
			$this->equalTo('UnderscoredName')
		);
	}
}
