<?php
require_once 'PHPUnit/Framework.php';

/**
 * Test class for BasicViewLoadListener.
 * Generated by PHPUnit on 2010-04-26 at 18:06:18.
 */
class BasicViewLoadListenerTest extends PHPUnit_Framework_TestCase
{
	/**
	 * @var BasicViewLoadListener
	 */
	protected $object;

	protected function setUp()
	{
		$paths = new PathCollection(array());
		$this->object = new BasicViewLoadListener($paths);
	}

	protected function tearDown()
	{
	}

	public function testHandle()
	{
	}
}
