<?php
require_once 'PHPUnit/Framework.php';

/**
 * Test class for ControllerInvokeListener.
 * Generated by PHPUnit on 2010-04-26 at 18:06:19.
 */
class ControllerInvokeListenerTest extends PHPUnit_Framework_TestCase
{
	/**
	 * @var ControllerInvokeListener
	 */
	protected $object;

	protected function setUp()
	{
		$mock = $this->getMock('IActionInvoker');
		$this->object = new ControllerInvokeListener($mock);
	}

	protected function tearDown()
	{
	}

	public function testHandle()
	{
	}
}
