<?php
require_once 'PHPUnit/Framework.php';

/**
 * Test class for ControllerLoadListener.
 * Generated by PHPUnit on 2010-04-26 at 18:06:20.
 */
class ControllerLoadListenerTest extends PHPUnit_Framework_TestCase
{
	/**
	 * @var ControllerLoadListener
	 */
	protected $object;

	protected function setUp()
	{
		$mock = $this->getMock('IControllerLoader');
		$this->object = new ControllerLoadListener($mock);
	}

	protected function tearDown()
	{
	}

	public function testHandle()
	{
	}
}
