<?php
require_once 'PHPUnit/Framework.php';

/**
 * Test class for RouteLoadListener.
 * Generated by PHPUnit on 2010-04-26 at 18:06:20.
 */
class RouteLoadListenerTest extends PHPUnit_Framework_TestCase
{
	/**
	 * @var RouteLoadListener
	 */
	protected $object;

	protected function setUp()
	{
		$mock = $this->getMock('IRouter');
		$this->object = new RouteLoadListener($mock);
	}

	protected function tearDown()
	{
	}

	public function testHandle()
	{
	}
}
