<?php
require_once 'PHPUnit/Framework.php';

/**
 * Test class for RouteLoadListener.
 * Generated by PHPUnit on 2010-04-26 at 18:06:20.
 */
class RouteLoadListenerTest extends PHPUnit_Framework_TestCase
{
	/**
	 * @var RouteLoadListener
	 */
	protected $object;

	protected function setUp()
	{
	}

	protected function tearDown()
	{
	}

	public function testHandle()
	{
		$router  = $this->getMock('IRouter');
		$router->expects($this->once())->method('fetchRoute')
			->will($this->returnValue('route instance'));
		$request = $this->getMock('IRequest');
		$this->object = new RouteLoadListener($router);

		$event = new Event($this, 'route.load', array(
			'request' => $request
		));

		$this->assertThat(
			$this->object->handle($event),
			$this->equalTo(true)
		);

		$this->assertThat(
			$event->getValue(),
			$this->equalTo('route instance')
		);
	}

	public function testHandle_NotSuccessful()
	{
		$router  = $this->getMock('IRouter');
		$router->expects($this->once())->method('fetchRoute')
			->will($this->returnValue(false));
		$request = $this->getMock('IRequest');
		$this->object = new RouteLoadListener($router);

		$event = new Event($this, 'route.load', array(
			'request' => $request
		));

		$this->assertThat(
			$this->object->handle($event),
			$this->equalTo(false)
		);
	}
}
