<?php
require_once 'PHPUnit/Framework.php';

/**
 * Test class for FrameworkPackage.
 * Generated by PHPUnit on 2010-04-27 at 14:51:26.
 */
class FrameworkPackageTest extends PHPUnit_Framework_TestCase
{
	/**
	 * @var FrameworkPackage
	 */
	protected $object;

	protected function setUp()
	{
		$this->object = new FrameworkPackage();
	}

	protected function tearDown()
	{
	}

	public function testGetPackageName()
	{
		$this->assertThat(
			$this->object->getPackageName(),
			$this->equalTo('Framework')
		);
	}

	public function testRegisterPackages()
	{
		$this->assertThat(
			$this->object->registerPackages(),
			$this->equalTo(array())
		);
	}

	public function testRegisterPaths()
	{
		$this->assertThat(
			$this->object->registerPaths(),
			$this->equalTo(null)
		);
	}

	public function testRegisterWiring()
	{
		$builder = $this->getMock('IContainerBuilder');
		$builder->expects($this->exactly(2))->method('merge')
			->with($this->isInstanceOf('IContainerBuilder'));
		$this->object->registerWiring($builder);
	}

	public function testRegisterClassLoaders()
	{
		$loaders = $this->object->registerClassLoaders();
		foreach ($loaders as $loader)
		{
			$this->assertThat(
				$loader,
				$this->isInstanceOf('IClassLoader')
			);
		}
	}
}
