<?php
require_once 'PHPUnit/Framework.php';

/**
 * Test class for CompiledRule.
 * Generated by PHPUnit on 2010-02-24 at 18:07:21.
 */
class CompiledRuleTest extends PHPUnit_Framework_TestCase
{
	/**
	 * @var CompiledRule
	 */
	protected $object;

	/**
	 *
	 * @var IRoutingRule
	 */
	protected $rule;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp()
	{
		$this->rule   = $this->getMock('IRoutingRule');
		$this->object = new CompiledRule($this->rule, '/^regex$/');
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown()
	{
	}

	public function testGetRule()
	{
		$this->assertEquals(
			$this->rule,
			$this->object->getRule()
		);
	}

	public function testGetRegex()
	{
		$this->assertEquals(
			'/^regex$/',
			$this->object->getRegex()
		);
	}

}
?>
