<?php
require_once 'PHPUnit/Framework.php';

/**
 * Test class for RoutingRule.
 * Generated by PHPUnit on 2010-02-23 at 16:08:51.
 */
class RoutingRuleTest extends PHPUnit_Framework_TestCase
{
	/**
	 * @var RoutingRule
	 */
	protected $o;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp()
	{
		$this->o = new RoutingRule(
			'defaultRoute',
			'/',
			array(
				'package'    => 'Frontend',
				'controller' => 'Home',
				'action'     => 'Index'
			),
			array(
				'controller'=>'string'
			)
		);
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown()
	{
	}

	public function testGetName()
	{
		$this->assertEquals(
			'defaultRoute',
			$this->o->getName()
		);
	}

	public function testGetPattern()
	{
		$this->assertEquals(
			'/',
			$this->o->getPattern()
		);
	}

	public function testGetParameters()
	{
		$this->assertEquals(
			array(
				'package' => 'Frontend',
				'controller'=>'Home',
				'action'=>'Index'
			),
			$this->o->getParameters()
		);
	}

	public function testGetParameter()
	{
		$this->assertThat(
			$this->o->getParameter('package'),
			$this->equalTo('Frontend')
		);

		$this->assertThat(
			$this->o->getParameter('undefined'),
			$this->equalTo(null)
		);

		$this->assertThat(
			$this->o->getParameter('undefined', 'default'),
			$this->equalTo('default')
		);
	}

	public function testGetRequirements()
	{
		$this->assertEquals(
			array('controller'=>'string'),
			$this->o->getRequirements()
		);
	}

}
