<?php

require_once 'PHPUnit/Framework.php';

/**
 * Test class for ArrayArgument.
 * Generated by PHPUnit on 2010-03-13 at 13:59:48.
 */
class ArrayArgumentTest extends PHPUnit_Framework_TestCase
{
	/**
	 * @var ArrayArgument
	 */
	protected $object;

	/**
	 * @var IDependencyInjectionContainer
	 */
	protected $container;

	/**
	 * @var IComponentAdapter
	 */
	protected $adapter;

	protected function setUp()
	{
		$this->container = $this->getMock('IDependencyInjectionContainer');
		$this->adapter   = $this->getMock('IComponentAdapter');


		$args = array();
		for ($i = 0; $i < 5; $i++)
		{
			$arg = $this->getMock('IComponentArgument', array('resolve'));
			$arg->expects($this->any())
				->method('resolve')
				->with(
					$this->equalTo($this->container),
					$this->equalTo($this->adapter)
				)
				->will($this->returnValue($i));

			$args[] = $arg;
		}

		$this->object = new ArrayArgument($args);
	}

	protected function tearDown()
	{
	}

	public function testResolve()
	{
		$result = $this->object->resolve($this->container, $this->adapter);

		$this->assertEquals(array('0', '1', '2', '3', '4'), $result);
	}
}
