<?php

require_once 'PHPUnit/Framework.php';

/**
 * Test class for ConstantArgument.
 * Generated by PHPUnit on 2010-03-13 at 14:32:27.
 */
class ConstantArgumentTest extends PHPUnit_Framework_TestCase
{
	/**
	 * @var ConstantArgument
	 */
	protected $object;

	/**
	 * @var IDependencyInjectionContaier
	 */
	protected $container;

	protected function setUp()
	{
		$this->object = new ConstantArgument('constant');
		$this->container = $this->getMock('IDependencyInjectionContainer');
		$this->container->expects($this->any())
			->method('getConstant')
			->will($this->returnValue('value'));
	}

	protected function tearDown()
	{
	}

	public function testResolve()
	{
		$value = $this->object->resolve(
			$this->container,
			$this->getMock('IComponentAdapter')
		);

		$this->assertThat(
			'value',
			$this->equalTo($value)
		);
	}

	public function testWithException()
	{
		$this->setExpectedException('InjecteeArgumentException');

		$value = $this->object->resolve(
			$this->getMock('IDependencyInjectionContainer'),
			$this->getMock('IComponentAdapter')
		);
	}
}
