<?php
require_once 'PHPUnit/Framework.php';

/**
 * Test class for BaseController.
 * Generated by PHPUnit on 2010-04-26 at 21:12:55.
 */
class BaseControllerTest extends PHPUnit_Framework_TestCase
{
	/**
	 * @var BaseController
	 */
	protected $object;

	protected function setUp()
	{
		$this->object = new BaseControllerStub();
	}

	protected function tearDown()
	{
	}

	public function testIsAbstract()
	{
		$reflection = new ReflectionClass('BaseController');
		$this->assertThat(
			$reflection->isAbstract(),
			$this->equalTo(true)
		);
	}

	public function testSetContainer()
	{
		$mock = $this->getMock('IDependencyInjectionContainer');
		$this->object->setContainer($mock);
		$this->assertThat(
			$this->object->getContainer(),
			$this->identicalTo($mock)
		);
	}

	public function testGetContainer()
	{
		$this->assertThat(
			$this->object->getContainer(),
			$this->equalTo(null)
		);
	}
}

class BaseControllerStub extends BaseController {}
