<?php

require_once 'PHPUnit/Framework.php';

require_once TEST_ROOT.'/Fixtures/Components/DependencyInjection/classes.php';

/**
 * Test class for ComponentArgument.
 * Generated by PHPUnit on 2010-03-13 at 13:59:59.
 */
class ComponentArgumentTest extends PHPUnit_Framework_TestCase
{
	/**
	 * @var ComponentArgument
	 */
	protected $object;

	/**
	 * @var IDependencyInjectionContainer
	 */
	protected $container;

	protected $against;

	protected function setUp()
	{
		$this->object = new ComponentArgument('my_component_key');
		$this->against = new WeakPunch();

		$this->container = $this->getMock('IDependencyInjectionContainer');
		$this->container->expects($this->any())
			->method('getInstanceOf')
			->will($this->returnValue($this->against));
	}

	protected function tearDown()
	{
	}

	public function testResolve()
	{
		$instance = $this->object->resolve(
			$this->container, $this->getMock('IComponentAdapter')
		);

		$this->assertThat(
			$this->against,
			$this->equalTo($instance)
		);
	}
}
