<?php

require_once 'PHPUnit/Framework.php';

/**
 * Test class for ValueArgument.
 * Generated by PHPUnit on 2010-03-13 at 14:37:40.
 */
class ValueArgumentTest extends PHPUnit_Framework_TestCase
{
	/**
	 * @var ValueArgument
	 */
	protected $object;

	protected function setUp()
	{
		$this->object = new ValueArgument('my value');
	}

	protected function tearDown()
	{
	}

	public function testResolve()
	{
		$value = $this->object->resolve(
			$this->getMock('IDependencyInjectionContainer'),
			$this->getMock('IComponentAdapter')
		);

		$this->assertEquals('my value', $value);
	}
}
