<?php
require_once 'PHPUnit/Framework.php';

/**
 * Test class for InstanceComponentAdapter.
 * Generated by PHPUnit on 2010-03-12 at 19:36:28.
 */
class InstanceComponentAdapterTest extends PHPUnit_Framework_TestCase
{
	/**
	 * @var InstanceComponentAdapter
	 */
	protected $object;

	protected $instance;

	protected $key;

	protected function setUp()
	{
		$this->key      = 'some_key';
		$this->instance = new stdClass();
		$this->object   = new InstanceComponentAdapter(
			$this->key, $this->instance
		);
	}

	protected function tearDown()
	{
	}

	public function testGetClass()
	{
		$this->assertThat(
			'stdClass',
			$this->equalTo($this->object->getClass())
		);
	}

	public function testGetInstance()
	{
		$container = $this->getMock('IDependencyInjectionContainer');
		$this->assertThat(
			$this->instance,
			$this->identicalTo($this->object->getInstance($container))
		);
	}

	public function testGetKey()
	{
		$this->assertThat(
			$this->key,
			$this->equalTo($this->object->getKey())
		);
	}
}
