<?php

require_once 'PHPUnit/Framework.php';

require_once TEST_ROOT.'/Fixtures/Components/DependencyInjection/classes.php';

/**
 * Test class for SharedComponentAdapter.
 * Generated by PHPUnit on 2010-03-13 at 13:48:16.
 */
class SharedComponentAdapterTest extends PHPUnit_Framework_TestCase
{
	/**
	 * @var SharedComponentAdapter
	 */
	protected $object;

	/**
	 * @var WeakPunch
	 */
	protected $against;

	protected function setUp()
	{
		$this->against = new WeakPunch();
		$mock = $this->getMock('IComponentAdapter');
		$mock->expects($this->any())
			->method('getInstance')
			->will($this->returnValue($this->against));
		$mock->expects($this->any())
			->method('getKey')
			->will($this->returnValue('weak_punch_component'));
		$mock->expects($this->any())
			->method('getClass')
			->will($this->returnValue('WeakPunch'));

		$this->object = new SharedComponentAdapter($mock);
	}

	protected function tearDown()
	{
	}

	public function testGetKey()
	{
		$this->assertThat(
			'weak_punch_component',
			$this->equalTo($this->object->getKey())
		);
	}

	public function testGetClass()
	{
		$this->assertThat(
			'WeakPunch',
			$this->equalTo($this->object->getClass())
		);
	}

	public function testGetInstance()
	{
		$container = $this->getMock('IDependencyInjectionContainer');
		$instance = $this->object->getInstance($container);

		$this->assertThat(
			$instance,
			$this->identicalTo($this->object->getInstance($container))
		);
	}
}
