<?php
require_once 'PHPUnit/Framework.php';

/**
 * Test class for ArrayStorage.
 * Generated by PHPUnit on 2010-04-27 at 12:58:47.
 */
class ArrayStorageTest extends PHPUnit_Framework_TestCase
{
	/**
	 * @var ArrayStorage
	 */
	protected $object;

	protected function setUp()
	{
		$this->object = new ArrayStorage(array(
			'initial' => 'data'
		));
	}

	protected function tearDown()
	{
	}

	public function testRead()
	{
		$this->assertThat(
			$this->object->read('undefined', 'default'),
			$this->equalTo('default')
		);
		$this->assertThat(
			$this->object->read('undefined'),
			$this->equalTo(null)
		);
		$this->assertThat(
			$this->object->read('initial'),
			$this->equalTo('data')
		);
	}

	public function testWrite()
	{
		$this->object->write('key', 'value');
		$this->assertThat(
			$this->object->read('key'),
			$this->equalTo('value')
		);
	}

	public function testDelete()
	{
		$this->object->delete('initial');
		$this->assertThat(
			$this->object->read('initial'),
			$this->equalTo(null)
		);
	}

	public function testRegenerate()
	{
		// nothing to test, nothing happens
		$this->object->regenerate();
	}
}
