<?php
require_once 'PHPUnit/Framework.php';

/**
 * Test class for SessionStorage.
 * Generated by PHPUnit on 2010-04-26 at 11:34:56.
 */
class SessionStorageTest extends PHPUnit_Framework_TestCase
{
	/**
	 * @var SessionStorage
	 */
	protected $object;

	protected function setUp()
	{
		$this->object = new SessionStorage('MY_NAME');
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown()
	{
	}

	public function testRead()
	{
		$this->assertThat(
			$this->object->read('undefined', 'default value'),
			$this->equalTo('default value')
		);
	}

	public function testWrite()
	{
		$this->object->write('some', 'data');

		$this->assertThat(
			$this->object->read('some'),
			$this->equalTo('data')
		);
	}

	public function testDelete()
	{
		$this->object->write('some', 'data');
		$this->object->delete('some');

		$this->assertThat(
			$this->object->read('some'),
			$this->equalTo(null)
		);
	}

	public function testRegenerate()
	{
		$firstId  = session_id();
		$this->object->regenerate(true);
		$secondId = session_id();

		$this->assertThat(
			$firstId,
			$this->logicalNot($this->equalTo($secondId))
		);
	}
}
