<?php
require_once 'PHPUnit/Framework.php';

/**
 * Test class for Logger.
 * Generated by PHPUnit on 2010-04-27 at 16:53:19.
 */
class LoggerTest extends PHPUnit_Framework_TestCase
{
	/**
	 * @var Logger
	 */
	protected $object;

	protected function setUp()
	{
		$handler = $this->getMock('ILogMessageHandler');
		$this->object = new Logger($handler);
	}

	protected function tearDown()
	{
	}

	public function testEmergency()
	{
	}

	public function testAlert()
	{
	}

	public function testCritical()
	{
	}

	public function testError()
	{
	}

	public function testWarning()
	{
	}

	public function testNotice()
	{
	}

	public function testInfo()
	{
	}

	public function testDebug()
	{
	}
}
