<?php
require_once 'PHPUnit/Framework.php';

/**
 * Test class for NullLogger.
 * Generated by PHPUnit on 2010-04-27 at 21:01:57.
 */
class NullLoggerTest extends PHPUnit_Framework_TestCase
{
	/**
	 * @var NullLogger
	 */
	protected $object;

	protected function setUp()
	{
		$this->object = new NullLogger();
	}

	protected function tearDown()
	{
	}

	public function testEmergency()
	{
		$this->object->emergency('message');
	}

	public function testAlert()
	{
		$this->object->alert('message');
	}

	public function testCritical()
	{
		$this->object->critical('message');
	}

	public function testError()
	{
		$this->object->error('message');
	}

	public function testWarning()
	{
		$this->object->warning('message');
	}

	public function testNotice()
	{
		$this->object->notice('message');
	}

	public function testInfo()
	{
		$this->object->info('message');
	}

	public function testDebug()
	{
		$this->object->debug('message');
	}

	public function testEmergency_WithAdditional()
	{
		$this->object->emergency('message', 'additional');
	}
}
