<?php
require_once 'PHPUnit/Framework.php';

/**
 * Test class for StringUtil.
 * Generated by PHPUnit on 2010-04-13 at 13:11:13.
 */
class StringUtilTest extends PHPUnit_Framework_TestCase
{
	public function testCamelize()
	{
		$this->assertThat(
			StringUtil::camelize('word'),
			$this->equalTo('Word')
		);

		$this->assertThat(
			StringUtil::camelize('main-controller'),
			$this->equalTo('MainController')
		);

		$this->assertThat(
			StringUtil::camelize('main_controller_class'),
			$this->equalTo('MainControllerClass')
		);

		$this->assertThat(
			StringUtil::camelize('some undefined words'),
			$this->equalTo('SomeUndefinedWords')
		);
	}
}
