<?php
require_once 'PHPUnit/Framework.php';

/**
 * Test class for StringUtil.
 * Generated by PHPUnit on 2010-04-13 at 13:11:13.
 */
class StringUtilTest extends PHPUnit_Framework_TestCase
{
	public function testCamelize()
	{
		$this->assertThat(
			StringUtil::camelize('word'),
			$this->equalTo('Word')
		);

		$this->assertThat(
			StringUtil::camelize('main-controller'),
			$this->equalTo('MainController')
		);

		$this->assertThat(
			StringUtil::camelize('main_controller_class'),
			$this->equalTo('MainControllerClass')
		);

		$this->assertThat(
			StringUtil::camelize('some undefined words'),
			$this->equalTo('SomeUndefinedWords')
		);
	}

	public function testSlugify()
	{
		$this->assertThat(
			StringUtil::slugify('Hello World!'),
			$this->equalTo('hello-world')
		);

		$this->assertThat(
			StringUtil::slugify('Mäkčene a dĺžne'),
			$this->equalTO('makcene-a-dlzne')
		);

		$this->assertThat(
			StringUtil::slugify('more  hyphens -- and   blanks'),
			$this->equalTo('more-hyphens-and-blanks')
		);

		$this->assertThat(
			StringUtil::slugify('verbose (with explanation in parens)'),
			$this->equalTo('verbose-with-explanation-in-parens')
		);

		$this->assertThat(
			StringUtil::slugify('with not standard characters at end !!>?>:'),
			$this->equalTo('with-not-standard-characters-at-end')
		);
	}
}
