<?php
require_once 'PHPUnit/Framework.php';

/**
 * Test class for AbstractComponentAdapter.
 * Generated by PHPUnit on 2010-03-12 at 17:17:10.
 */
class AbstractComponentAdapterTest extends PHPUnit_Framework_TestCase
{
	/**
	 * @var AbstractComponentAdapter
	 */
	protected $object;

	public function testCannotInstantiate()
	{
		$reflection = new ReflectionClass('AbstractComponentAdapter');
		$this->assertFalse(
			$reflection->isInstantiable(),
			'Class is defined as ABSTRACT, therefore can\'t be instantiated'
		);
	}
	
}
?>
