<?php
require_once 'PHPUnit/Framework.php';

/**
 * Test class for ApplicationFactory.
 * Generated by PHPUnit on 2010-04-18 at 19:41:02.
 */
class ApplicationFactoryTest extends PHPUnit_Framework_TestCase
{
	/**
	 * @var ApplicationFactory
	 */
	protected $object;

	protected function setUp()
	{
		$this->object = new ApplicationFactory();
	}

	protected function tearDown()
	{
	}

	public function testCreateContainer()
	{
		$this->assertThat(
			$this->object->createContainer(),
			$this->isInstanceOf('IDependencyInjectionContainer')
		);
	}

	public function testCreateContainerBuilder()
	{
		$this->assertThat(
			$this->object->createContainerBuilder(),
			$this->isInstanceOf('IContainerBuilder')
		);
	}
}
