<?php
require_once 'PHPUnit/Framework.php';

/**
 * Test class for PathCollection.
 * Generated by PHPUnit on 2010-04-20 at 10:41:13.
 */
class PathCollectionTest extends PHPUnit_Framework_TestCase
{
	/**
	 * @var PathCollection
	 */
	protected $object;

	protected function setUp()
	{
		$this->object = new PathCollection();
	}

	protected function tearDown()
	{
	}

	public function testSetPaths()
	{
		$this->object->setPaths(array(
			'testing.purpose' => array(FIXTURES_ROOT),
			'another'         => array(dirname(__FILE__)),
		));
		$this->assertThat(
			$this->object->getAll(),
			$this->equalTo(array(FIXTURES_ROOT, dirname(__FILE__)))
		);
	}

	public function testAddPath()
	{
		$this->object->addPath('testing.fixtures', FIXTURES_ROOT);
		$this->assertThat(
			$this->object->getPaths('testing.fixtures'),
			$this->equalTo(array(FIXTURES_ROOT))
		);
	}

	public function testAddPath_FailsAtUndefinedDirectory()
	{
		$this->setExpectedException('UnexpectedValueException');
		$this->object->addPath('fails', FIXTURES_ROOT.'/Undefined_Directory');
	}

	public function testGetPaths()
	{
		$this->assertThat(
			$this->object->getPaths('undefined.type'),
			$this->equalTo(array())
		);
	}

	public function testGetAll()
	{
		$this->assertThat(
			$this->object->getAll(),
			$this->equalTo(array())
		);
	}
}
