<?php
require_once 'PHPUnit/Framework.php';

/**
 * Test class for WebApplication.
 * Generated by PHPUnit on 2010-04-27 at 13:29:32.
 */
class WebApplicationTest extends PHPUnit_Framework_TestCase
{
	/**
	 * @var WebApplication
	 */
	protected $object;

	/**
	 * @var DependencyInjectionContainer
	 */
	protected $container;

	protected function setUp()
	{
		$this->object = new WebApplicationStub_TestSuite('prod', false);
		$this->container = $this->object->getContainer();
		$this->container->define('event_emitter_service')
			->setClass('LazyEventEmitter');
		$this->container->define('sample_listener')
			->addNote('listener', array(
				array('sample.event', 'resolve'),
			));
		$this->container->define('request_service')
			->setClass('Request');
		$this->container->define('controller_runner_service')
			->setClass('ControllerRunner');

		$this->container->define('router_service');
	}

	protected function tearDown()
	{
	}

	public function testRun()
	{
		$this->setExpectedException('NotFoundHttpException');
		$this->object->run();
	}

	public function testConfigure()
	{
		$this->object->configure();
		$array = array();
		$this->assertThat(
			$this->container->getConstant('controller.paths'),
			$this->equalTo($array)
		);
		$this->assertThat(
			$this->container->getConstant('command.paths'),
			$this->equalTo($array)
		);
		$this->assertThat(
			$this->container->getConstant('view.paths'),
			$this->equalTo($array)
		);
	}
}

class WebApplicationStub_TestSuite extends WebApplication
{
	public function registerRouting()
	{
		return array(
			new RoutingRule('sample', '{pattern}')
		);
	}
	public function registerPackages() {}
	public function registerPackagePaths() {}
	public function registerConfiguration() {}
}
