<?php
require_once 'PHPUnit/Framework.php';

/**
 * Test class for HttpStatusCode.
 * Generated by PHPUnit on 2010-04-23 at 19:56:40.
 */
class HttpStatusCodeTest extends PHPUnit_Framework_TestCase
{
	/**
	 * @var HttpStatusCode
	 */
	protected $object;

	protected function setUp()
	{
		$this->object = new HttpStatusCode();
	}

	protected function tearDown()
	{
	}

	public function testSetCode()
	{
		$this->object->setCode('404');
		$this->assertThat(
			$this->object->getCode(),
			$this->equalTo(404)
		);
	}

	public function testSetCode_InvalidCode()
	{
		$this->setExpectedException('InvalidArgumentException');
		$this->object->setCode(99);
	}

	public function testGetCode()
	{
		$this->assertThat(
			$this->object->getCode(),
			$this->equalTo(200)
		);
	}

	public function testGetText()
	{
		$this->assertThat(
			$this->object->getText(),
			$this->equalTo('OK')
		);
	}
}
