<?php
require_once 'PHPUnit/Framework.php';

/**
 * Test class for Request.
 * Generated by PHPUnit on 2010-04-23 at 20:11:06.
 */
class RequestTest extends PHPUnit_Framework_TestCase
{
	/**
	 * @var Request
	 */
	protected $object;

	protected function setUp()
	{
		$this->object = new Request();
	}

	protected function tearDown()
	{
	}

	public function testHasParameter()
	{
	}

	public function testGetParameter()
	{
	}

	public function testSetParameter()
	{
	}

	public function testHasCookie()
	{
	}

	public function testGetCookie()
	{
	}

	public function testHasServer()
	{
	}

	public function testGetServer()
	{
	}

	public function testIsSecure()
	{
	}

	public function testGetProtocol()
	{
	}

	public function testGetHost()
	{
	}

	public function testGetHttpHost()
	{
	}

	public function testGetMethod()
	{
	}

	public function testGetBasePath()
	{
	}

	public function testGetBaseUrl()
	{
	}

	public function testGetRequestUri()
	{
	}

	public function testGetPathInfo()
	{
	}

	public function testIsXmlHttpRequest()
	{
	}
}
