<?php
require_once 'PHPUnit/Framework.php';

/**
 * Test class for DefaultContainerFactory.
 * Generated by PHPUnit on 2010-03-13 at 15:26:35.
 */
class DefaultContainerFactoryTest extends PHPUnit_Framework_TestCase
{
	/**
	 * @var DefaultContainerFactory
	 */
	protected $object;

	protected function setUp()
	{
		$this->object = new DefaultContainerFactory(null);
	}

	protected function tearDown()
	{
	}

	public function testCreateContainerBuilder()
	{
		$builder = $this->object->createContainerBuilder();
		$this->assertThat($builder, $this->isInstanceOf('IContainerBuilder'));
	}

	public function testCreateComponentDefinition()
	{
		$definition = $this->object->createComponentDefinition('HelloClass', array());
		$this->assertThat($definition, $this->isInstanceOf('IComponentDefinition'));
	}

	public function testCreateInstanceAdapter()
	{
		$adapter = $this->object->createInstanceAdapter(null, new stdClass());
		$this->assertThat($adapter, $this->isInstanceOf('InstanceComponentAdapter'));
		$this->assertThat($adapter->getKey(), $this->equalTo(null));
	}

	public function testCreateConstructorAdapter()
	{
		$adapter = $this->object->createConstructorAdapter(null, 'HelloClass', array());
		$this->assertThat($adapter, $this->isInstanceOf('ConstructorComponentAdapter'));

	}

	public function testCreateAdapterFromDef()
	{
		$adapter = $this->object->createAdapterFromDef(new ComponentDefinition('HelloClass'));
		$this->assertThat($adapter, $this->isInstanceOf('IComponentAdapter'));
	}
}
