<?php
require_once 'PHPUnit/Framework.php';

/**
 * Test class for DefaultContainerFactory.
 * Generated by PHPUnit on 2010-03-13 at 15:26:35.
 */
class DefaultContainerFactoryTest extends PHPUnit_Framework_TestCase
{
	/**
	 * @var DefaultContainerFactory
	 */
	protected $object;

	protected function setUp()
	{
		$this->object = new DefaultContainerFactory;
	}

	protected function tearDown()
	{
	}

	public function testCreateComponentDefinition()
	{
	}

	public function testCreateInstanceAdapter()
	{
	}

	public function testCreateConstructorAdapter()
	{
	}

	public function testCreateAdapterFromDef()
	{
	}
}
